// <auto-generated />
using System;
using Euphorolog.Database.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Euphorolog.Database.Migrations
{
    [DbContext(typeof(EuphorologContext))]
    [Migration("20220801120341_migration8")]
    partial class migration8
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Euphorolog.Database.Models.Stories", b =>
                {
                    b.Property<string>("storyId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("authorName")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("createdAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("openingLines")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("storyDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("storyNo")
                        .HasColumnType("int");

                    b.Property<string>("storyTitle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("updatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("storyId");

                    b.HasIndex("authorName");

                    b.ToTable("stories");
                });

            modelBuilder.Entity("Euphorolog.Database.Models.Users", b =>
                {
                    b.Property<string>("userName")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("eMail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("fullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("passChangedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("passChangedflag")
                        .HasColumnType("bit");

                    b.Property<string>("password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("passwordHash")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<byte[]>("passwordSalt")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.HasKey("userName");

                    b.ToTable("users");
                });

            modelBuilder.Entity("Euphorolog.Database.Models.Stories", b =>
                {
                    b.HasOne("Euphorolog.Database.Models.Users", "Users")
                        .WithMany("stories")
                        .HasForeignKey("authorName")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Users");
                });

            modelBuilder.Entity("Euphorolog.Database.Models.Users", b =>
                {
                    b.Navigation("stories");
                });
#pragma warning restore 612, 618
        }
    }
}
